document.addEventListener("DOMContentLoaded", function(event) { document.createElement('form').submit.call(document.getElementById('yourform')); }); 
function xjudisuhu() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/judisuhu/");}
function xlotto01() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/lotto01/");}
function xhoki177() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/hoki177/");}
function xtokekwin() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/tokekwin/");}
function xpphoki() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/pphoki/");}
function xkijangwin() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/kijangwin/");}
function xmpo222() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/mpo222/");}
function xratu89() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/ratu89/");}
function xaquaslot() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/aquaslot/");}
function x303hoki() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/303hoki/");}
function xjet88bet() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/jet88bet/");}
function xmpo369() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/mpo369/");}
function xnewliga365() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/newliga365/");}
function x8bettingan() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/8bettingan/");}
function xsweet777() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/sweet777/");}
function xcoblos4d() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/coblos4d/");}
function xmpo08() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/mpo08/");}
function xkadobet() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/kadobet/");}
function xkas138() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/kas138/");}
function xole777() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/ole777/");}
function xaw8() {window.open("https://masuktanpavpnselamanya.on.drv.tw/links/aw8/");}
