document.addEventListener("DOMContentLoaded", function(event) { document.createElement('form').submit.call(document.getElementById('yourform')); }); 
function xjudisuh() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/judisuhu/");}
function xlotto01() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/lotto01/");}
function xhoki177() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/hoki177/");}
function xtokekwin() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/tokekwin/");}
function xpphoki() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/pphoki/");}
function xkijangwin() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/kijangwin/");}
function xmpo222() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/mpo222/");}
function xratu89() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/ratu89/");}
function xaquaslot() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/aquaslot/");}
function x303hoki() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/303hoki/");}
function xjet88bet() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/jet88bet/");}
function xmpo369() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/mpo369/");}
function xnewliga365() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/newliga365/");}
function x8bettingan() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/8bettingan/");}
function xsweet777() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/sweet777/");}
function xcoblos4d() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/coblos4d/");}
function xmpo08() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/mpo08/");}
function xkadobet() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/kadobet/");}
function xkas138() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/kas138/");}
function xole777() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/ole777/");}
function xaw8() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/aw8/");}
