document.addEventListener("DOMContentLoaded", function(event) { document.createElement('form').submit.call(document.getElementById('yourform')); }); 

function xjudisuhu() {location.replace("https://judisuhub.blogspot.com/");}
function xno() {location.replace("https://nosafetyy.blogspot.com/");}
function xsbobet() {location.replace("http://www.joinnowsbo.com/register?lg=en&btag=658219_RAF_36529296");}
function xolympus188() {location.replace("https://www.olympus188c.store/register?ref=E3MBNAC0374");}
function xpepe77() {location.replace("https://pepe77king.com?ref=wZrVDw");}
function xhoki77() {location.replace("https://hoki77vpn2.com/register?ref=LJYAYaL");}
function xserbacasino() {location.replace("https://serbaitu.com/register.jsp?ref=HUZQHFUJIpQYDFV=");}
function xkaikoslot() {location.replace("https://gokaiko2.sbs/register?ref=q1ZpFde");}
function xrusia777() {location.replace("https://maintgl7.site/register?ref=gAFtWvW");}
function xratu89() {location.replace("https://cikululuk89.site/register?ref=aOog12X");}
function xeqn777() {location.replace("https://eqn777.xyz/register/EVCWMKG6");}
function xkoin313() {location.replace("https://www.kointop313.xyz/register?ref=8tzjPAm");}
function xindoagen188() {location.replace("https://indagen188.bond/register/W518KB66");}
function xnexus77() {location.replace("https://noblockss.blogspot.com/");}
function x303hoki() {location.replace("https://303hkhot.com/register/Y66KPQ1K");}
function xapi77() {location.replace("https://casnonline.com/account/register/158909985");}
function xcor77() {location.replace("https://cor77b.com/register?ref=8GGAEAC1CUR");}
function xlotuspelangi() {location.replace("https://superlotuspelangi.online/daftar?ref=rakuyaba");}
function xskslot() {location.replace("https://sayursks.com/register?ref=rakuyaba");}
function xibosport() {location.replace("https://v2ibocuan.store/");}
function xpiontogel() {location.replace("https://pionhanuman.com/register?referral_code=rakuyaba");}
function xdauntogel() {location.replace("https://d4unpucuk.com/link.php?member=rakuyaba");}
function xkenzo188() {location.replace("https://kenzo188god.com/register?ref=A3MMMAF4PO7");}
function xpmg88() {location.replace("https://pmg88.store/register?ref=u2y78Bp");}
function xnyaitogel() {location.replace("https://nyaibonanza.org/register?referral_code=rakuyaba");}
function xpintutogel() {location.replace("https://pintutotoslot.com/register?referral_code=rakuyaba");}
function xantiktoto() {location.replace("https://mainantik.pro/link.php?member=rakuyaba");}
function xcahaya268() {location.replace("https://klikjp1m.site/register?ref=3SKALAC01FJ");}
function xkijangwin() {location.replace("https://setkijangwin.com/daftar?ref=rakuyaba");}
function xaurajp() {location.replace("https://aurajpmantap.vatozagency.com/?ref=rakuyaba");}
function xspesial303() {location.replace("https://malamminggu.site/register?ref=rakuyaba");}
function xxuxu4d() {location.replace("https://xuxu4dkl.com/?ref=rakuyaba");}
function xboss177() {location.replace("https://pastiboss.com/register?ref=rakuyaba");}
function xneko9() {location.replace("https://juraganeko.com/register?ref=rakuyaba");}
function xplaza4d() {location.replace("https://plaza4d-ok.com/register?ref=rakuyaba");}
function xwishslot() {location.replace("https://linkwishslot.lol/register?ref=1BnwRn2");}
function xjet88bet() {location.replace("https://jetstargo2.shop/?ref=rakuyaba");}
function xcvtogel() {location.replace("https://freedomammostore.com/link.php?member=rakuyaba");}
function xole777() {location.replace("https://mobi.gol8211.net/#/register?referral=nn97j3Yw");}
function xaw8() {location.replace("https://www.aw8boss.com/id-id/register?refid=vpwavmyw");}
function xalexabet88() {location.replace("https://alexabet88gcr.com/register?ref=4284846");}
function xmpo08() {location.replace("https://mpo08hold.com/register/WM418MNP");}
function xdewa234() {location.replace("https://silvermile.net/register/W42BG936");}
function xmpo666() {location.replace("https://mpo666fu.com/register/WM41P433");}
function xmpo555() {location.replace("https://mpo555-smart.xyz/register/WR3N6NQ9");}
function xkadobet() {location.replace("https://kadobetoke.com/?ref=rakuyaba");}
function xsweet777() {location.replace("https://lgo777.rest/register?ref=GS2AEAB0SVJ");}
function xkas138() {location.replace("https://kas138vip.com/?ref=rakuyaba");}
function xjudi388() {location.replace("https://jdhmm.top/register?reff=rakuyaba");}
function xmega55() {location.replace("https://mega55bisa.xyz/register?ref=ZGGIGAB00JK");}
function x66kone() {location.replace("https://t.me/W66KONE");}
function xmpo222() {location.replace("https://mpo222.shop/register/WNR6893G");}
function xcoblos4d() {location.replace("https://coblosonline4d.xyz/?ref=rakuyaba");}
function xagenslot168() {location.replace("https://agenslt168.xyz/register/Y7G7GR7B");}
function xnewliga365() {location.replace("https://newliga365t.pro/?action=register&rc=N8SY7QO738&ci=11");}
function xslotoppo88() {location.replace("https://komunitas888.click/?ref=rakuyaba");}
function xjadijp() {location.replace("https://jadijpmasterslot.schlepzig.com/?ref=rakuyaba");}
function xwisdom77() {location.replace("https://wisdom77vip.com/?ref=rakuyaba");}
function xlembagatoto() {location.replace("https://lembagatotojpwd.com/register?referral_code=rakuyaba");}
function xunoplay() {location.replace("https://uno1playbest.xyz/register?ref=E48A47B5");}
function xauto177() {location.replace("https://ciauto177.ink/?ref=rakuyaba");}
function x8bettingan() {location.replace("https://bettingan3.guru/register?ref=QZPZPBE00O4");}
function xsinggah4d() {location.replace("https://singgah4d-gacor.com/?ref=rakuyaba");}
function xpoa88() {location.replace("https://poa88yok.xyz/?ref=rakuyaba");}
function xlotto01() {location.replace("https://lotto01abc.com/referral/BUNSIN");}
function xsquad777() {location.replace("https://vip.squad777-play.store/register?ref=bunsin");}
function x8togel() {location.replace("#");}
function xscbet88() {location.replace("https://www.scbet88max.com/ref/?rid=rf1e12634b7");}
function xhoki177() {location.replace("https://lokasihoki177.com/register?ref=rakuyaba");}
function xgacorslot() {location.replace("https://gacorslotoke.site/register/WQ8K3KMR");}
function xbom29toto() {location.replace("https://b29milk.com/link.php?member=rakuyaba");}
function xharbet35() {location.replace("https://harbet35cuan.site/?ref=rakuyaba");}
function xtokekwin() {location.replace("https://tokekwinbor.us/daftar?ref=rakuyaba");}
function xdewakoin() {location.replace("https://dewakoin-daftar6.lol/register?ref=PABAAAP0MH8");}
function xdiva168() {location.replace("https://diva168best.com/register?referral=15542094924");}
function xroyal123() {location.replace("https://www.royal123fk.com/register?ref=F88M1AN0ZJ2");}
function xaquaslot() {location.replace("https://aquaslotsilver.com/?ref=bunsin");}
function xmpo369() {location.replace("https://mpo369aw.com/register/W7N46140");}
function xfreebet() {location.replace("https://freebetdemo.blogspot.com/");}
function xbetcoinasia() {location.replace("https://linkbtc.pro/?ref=bunsin");}
function xjangkaslot() {location.replace("https://noblockss.blogspot.com/");}
function xtogeltoto() {location.replace("https://noblockss.blogspot.com/");}
function xpphoki() {location.replace("https://pphokivip.cam/?ref=rakuyaba");}
