function lcxchattawk() {window.open("https://tawk.to/chat/65eec9ce8d261e1b5f6b705b/1homc8jr0");}
function lcxchatfb() {window.open("https://www.facebook.com/profile.php?id=61553499868790");}
function lcxsitus() {location.replace("#");}
function lcxdewakoin() {location.replace("./chat/dewakoin/index.html");}
function lcx8togel() {location.replace("./chat/8togel/index.html");}
function lcxdewa234() {location.replace("./chat/dewa234/index.html");}
function lcxunoplay() {location.replace("./chat/unoplay/index.html");}
function lcxhoki77() {location.replace("./chat/hoki77/index.html");}
function lcxjudi388() {location.replace("./chat/judi388/index.html");}
function lcxsquad777() {location.replace("./chat/squad777/index.html");}
function lcxspesial303() {location.replace("./chat/spesial303/index.html");}
function lcxsbobet() {location.replace("./chat/sbobet/index.html");}
function lcxrusia777() {location.replace("./chat/rusia777/index.html");}
function lcxolympus188() {location.replace("./chat/olympus188/index.html");}
function lcxkoin313() {location.replace("./chat/koin313/index.html");}
function lcxxuxu4d() {location.replace("./chat/xuxu4d/index.html");}
function lcxmpo666() {location.replace("./chat/mpo666/index.html");}
function lcxdiva168() {location.replace("./chat/diva168/index.html");}
function lcxslotoppo88() {location.replace("./chat/slotoppo88/index.html");}
function lcxalexabet88() {location.replace("./chat/alexabet88/index.html");}
function lcxapi77() {location.replace("./chat/api77/index.html");}
function lcxindoagen188() {location.replace("./chat/indoagen188/index.html");}
function lcxscbet88() {location.replace("./chat/scbet88/index.html");}
function lcxpmg88() {location.replace("./chat/pmg88/index.html");}
function lcxsinggah4d() {location.replace("./chat/singgah4d/index.html");}
function lcxantiktoto() {location.replace("./chat/antiktoto/index.html");}
function lcxcahaya268() {location.replace("./chat/cahaya268/index.html");}
function lcxneko9() {location.replace("./chat/neko9/index.html");}
function lcx66kone() {location.replace("./chat/66kone/index.html");}
function lcxmega55() {location.replace("./chat/mega55/index.html");}
function lcxwishslot() {location.replace("./chat/wishslot/index.html");}
function lcxpintutogel() {location.replace("./chat/pintutogel/index.html");}
function lcxnyaitogel() {location.replace("./chat/nyaitogel/index.html");}
function lcxaurajp() {location.replace("./chat/aurajp/index.html");}
function lcxdauntogel() {location.replace("./chat/dauntogel/index.html");}
function lcxpiontogel() {location.replace("./chat/piontogel/index.html");}
function lcxjadijp() {location.replace("./chat/jadijp/index.html");}
function lcxcvtogel() {location.replace("./chat/cvtogel/index.html");}
function lcxmpo555() {location.replace("./chat/mpo555/index.html");}
function lcxwisdom77() {location.replace("./chat/wisdom77/index.html");}
function lcxharbet35() {location.replace("./chat/harbet35/index.html");}
function lcxpoa88() {location.replace("./chat/poa88/index.html");}
function lcxeqn777() {location.replace("./chat/eqn777/index.html");}
function lcxlembagatoto() {location.replace("./chat/lembagatoto/index.html");}
function lcxroyal123() {location.replace("./chat/royal123/index.html");}
function lcxgacorslot() {location.replace("./chat/gacorslot/index.html");}
function lcxagenslot168() {location.replace("./chat/agenslot168/index.html");}
function lcxskslot() {location.replace("./chat/skslot/index.html");}
function lcxlotuspelangi() {location.replace("./chat/lotuspelangi/index.html");}
function lcxplaza4d() {location.replace("./chat/plaza4d/index.html");}
function lcxkenzo188() {location.replace("./chat/kenzo188/index.html");}
function lcxkaikoslot() {location.replace("./chat/kaikoslot/index.html");}
function lcxbetcoinasia() {location.replace("./chat/betcoinasia/index.html");}
function lcxbom29toto() {location.replace("./chat/bom29toto/index.html");}
function lcxserbacasino() {location.replace("./chat/serbacasino/index.html");}
function lcxboss177() {location.replace("./chat/boss177/index.html");}
function lcxhedon77() {location.replace("./chat/hedon77/index.html");}
function lcxrajatoto3() {location.replace("./chat/rajatoto3/index.html");}
function lcxshiokambing() {location.replace("./chat/shiokambing/index.html");}
function lcxshiokambing2() {location.replace("./chat/shiokambing2/index.html");}
function lcxshiokambing5() {location.replace("./chat/shiokambing5/index.html");}
function lcxcabe777() {location.replace("./chat/cabe777/index.html");}
function lcxdewatogel() {location.replace("./chat/dewatogel/index.html");}
function lcxmpo888() {location.replace("./chat/mpo888/index.html");}
function lcxnagatop() {location.replace("./chat/nagatop/index.html");}
function lcxmansion77() {location.replace("./chat/mansion77/index.html");}
function lcxmega38() {location.replace("./chat/mega38/index.html");}
function lcxgacor88() {location.replace("./chat/gacor88/index.html");}
function lcxpreman69() {location.replace("./chat/preman69/index.html");}
function lcxjnt77() {location.replace("./chat/jnt77/index.html");}
function lcxsgpslot() {location.replace("./chat/sgpslot/index.html");}
function lcxindoslot88() {location.replace("./chat/indoslot88/index.html");}
function lcxjetplay88() {location.replace("./chat/jetplay88/index.html");}
function lcxnusabet() {location.replace("./chat/nusabet/index.html");}
function lcxtkp303() {location.replace("./chat/tkp303/index.html");}
function lcxvit88() {location.replace("./chat/vit88/index.html");}
function lcxadipatislot() {location.replace("./chat/adipatislot/index.html");}
function lcxbk8() {location.replace("./chat/bk8/index.html");}
function lcxflash303() {location.replace("./chat/flash303/index.html");}
function lcxfijislot() {location.replace("./chat/fijislot/index.html");}
function lcxmaxwin88() {location.replace("./chat/maxwin88/index.html");}
function lcxjackpot168() {location.replace("./chat/jackpot168/index.html");}
function lcxfungame777() {location.replace("./chat/fungame777/index.html");}
function lcxluxury333() {location.replace("./chat/luxury333/index.html");}
function lcxslotmacau188() {location.replace("./chat/slotmacau188/index.html");}
function lcxtektok77() {location.replace("./chat/tektok77/index.html");}
function lcxindogenting() {location.replace("./chat/indogenting/index.html");}
function lcxagen288() {location.replace("./chat/agen288/index.html");}
function lcxrahayu88() {location.replace("./chat/rahayu88/index.html");}
function lcxneo177() {location.replace("./chat/neo177/index.html");}
function lcxbagus88() {location.replace("./chat/bagus88/index.html");}
function lcxareabola() {location.replace("./chat/areabola/index.html");}
function lcxdafabet() {location.replace("./chat/dafabet/index.html");}
function lcxraja168() {location.replace("./chat/raja168/index.html");}
function lcxkiw69() {location.replace("./chat/kiw69/index.html");}
function lcxwis77() {location.replace("./chat/wis77/index.html");}
function lcxhokiwin() {location.replace("./chat/hokiwin/index.html");}
function lcxzona66() {location.replace("./chat/zona66/index.html");}
function lcxkudetabet98() {location.replace("./chat/kudetabet98/index.html");}
function lcxmpo333() {location.replace("./chat/mpo333/index.html");}
function lcxjitu77() {location.replace("./chat/jitu77/index.html");}
function lcxeraplay88() {location.replace("./chat/eraplay88/index.html");}
function lcxmpo111() {location.replace("./chat/mpo111/index.html");}
function lcxmpo999() {location.replace("./chat/mpo999/index.html");}
function lcxmpo777() {location.replace("./chat/mpo777/index.html");}
function lcxamanah77() {location.replace("./chat/amanah77/index.html");}
function lcxligahoki89() {location.replace("./chat/ligahoki89/index.html");}
function lcxrajampo() {location.replace("./chat/rajampo/index.html");}
function lcxibutogel() {location.replace("./chat/ibutogel/index.html");}
function lcxsupertogel() {location.replace("./chat/supertogel/index.html");}
function lcxamavi88() {location.replace("./chat/amavi88/index.html");}
function lcxbaron4d() {location.replace("./chat/baron4d/index.html");}
function lcxw77() {location.replace("./chat/w77/index.html");}
function lcxjoki55() {location.replace("./chat/joki55/index.html");}
function lcxmegabandar() {location.replace("./chat/megabandar/index.html");}
function lcxtwinbet() {location.replace("./chat/twinbet/index.html");}
function lcxdewasloto() {location.replace("./chat/dewasloto/index.html");}
function lcxwanatoto() {location.replace("./chat/wanatoto/index.html");}
function lcxkingtoto() {location.replace("./chat/kingtoto/index.html");} 
function lcxajr88() {location.replace("./chat/ajr88/index.html");} 
function lcxhoki178() {location.replace("./chat/hoki178/index.html");}
function lcxdewagacor77() {location.replace("./chat/dewagacor77/index.html");}
function lcxkudapoker() {location.replace("./chat/kudapoker/index.html");}
function lcxvipbet88() {location.replace("./chat/vipbet88/index.html");}
function lcxpesiar88() {location.replace("./chat/pesiar88/index.html");}
function lcxpokerbo() {location.replace("./chat/pokerbo/index.html");}
function lcxgacorbos88() {location.replace("./chat/gacorbos88/index.html");}
function lcxjawara88() {location.replace("./chat/jawara88/index.html");}
function lcxyakinslot88() {location.replace("./chat/yakinslot88/index.html");}
function lcxhoki138() {location.replace("./chat/hoki138/index.html");}
function lcxtatabet() {location.replace("./chat/tatabet/index.html");}
function lcxsatutogel() {location.replace("./chat/satutogel/index.html");}
function lcxdemen303() {location.replace("./chat/demen303/index.html");}
function lcxairbet88() {location.replace("./chat/airbet88/index.html");}
function lcxmusangwin() {location.replace("./chat/musangwin/index.html");}
function lcxn77toto() {location.replace("./chat/n77toto/index.html");}
function lcxmpocasino() {location.replace("./chat/mpocasino/index.html");}
function lcxome88() {location.replace("./chat/ome88/index.html");}
function lcxm88() {window.open("https://www.facebook.com/M88MansionOfficial/");}